### ISSUE TITLE
[Bug]  thread 'main' panicked at 'Could not determine the UTC offset on this system.'

### ISSUE THREAD

**Issue by Nightliss** [ravenclaw900/DietPi-Dashboard#82]
DietPI v7.9.3
DietPi-Dashboard - nightly, installed just now after updating to 7.9.3 and updating ports to 5252

```bash
dietpi@DietPi:~$ sudo systemctl status dietpi-dashboard
● dietpi-dashboard.service - Web Dashboard (DietPi)
     Loaded: loaded (/etc/systemd/system/dietpi-dashboard.service; enabled; vendor preset: enabled)
     Active: failed (Result: signal) since Thu 2021-12-16 21:09:29 GMT; 1min 5s ago
    Process: 2022734 ExecStart=/opt/dietpi-dashboard/dietpi-dashboard (code=killed, signal=ABRT)
   Main PID: 2022734 (code=killed, signal=ABRT)
        CPU: 7ms

Dec 16 21:09:29 DietPi systemd[1]: Started Web Dashboard (DietPi).
Dec 16 21:09:29 DietPi dietpi-dashboard[2022734]: thread 'main' panicked at 'Could not determine the UTC offset on this system. Possible causes are that the time crate does not implement "local_offset_at" on your system, or that you are running in a multi-threaded environment and the time crate is returning "None" from "local_offset_at" to avoid unsafe behaviour. See the time crate's documentation for more information. (https://time-rs.github.io/internal-api/time/index.html#feature-flags): IndeterminateOffset', /cargo/registry/src/github.com-1ecc6299db9ec823/simple_logger-1.16.0/src/lib.rs:409:85
Dec 16 21:09:29 DietPi dietpi-dashboard[2022734]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 16 21:09:29 DietPi systemd[1]: dietpi-dashboard.service: Main process exited, code=killed, status=6/ABRT
Dec 16 21:09:29 DietPi systemd[1]: dietpi-dashboard.service: Failed with result 'signal'.
```

**Comment by ravenclaw900** [comment]
Hello,
This is due to a new feature in the logging library which gets local timestamps. I'll set it to how it was before, to only use UTC timestamps.

**Comment by ravenclaw900** [comment]
Fixed with https://github.com/ravenclaw900/DietPi-Dashboard/commit/a3853c2697d5a0606499c41fc6cf456543e01a4e

**Comment by Nightliss** [comment]
Works fine, thank you :)
